# .github/workflows/ci.yml
name: Web CI

on:
  push:
    branches: [main, develop, feature/*, bugfix/*]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json  # Adjust if using yarn.lock

      - name: 📦 Install dependencies
        working-directory: web
        run: npm ci

      - name: 🧹 Lint code
        working-directory: web
        run: npm run lint

      - name: 🧪 Run tests
        working-directory: web
        run: npm test
